### ISSUE TITLE
Montar o forms de voluntariado baseado no modelo do ano passado. (@damariscampos26 )

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-org#19]

**Comment by damariscampos26** [comment]
Foi criado o formulário de voluntariado, e se encontra no link: https://drive.google.com/drive/folders/1Xr9XTcOnZa7lKLukc_kp6oAFyQOt8n8H?usp=sharing

O link para inscrição no formulário é: https://forms.gle/53iQoGFqhDimX8QKA
