### ISSUE TITLE
Entrar em contato com a UFAM de Itacoatiara (@MateusSantosMeuBem)

### ISSUE THREAD

**Issue by julianyraiol** [PyNorte/pynorte2024-org#2]
## Descrição

O resultado desta tarefa é a definição do local do evento em Itacoatiara

**Comment by meu-bem** [comment]
Eles gostaram bastante da proposta. Estou aguardando definirmos a programação do evento para solicitar o espaço junto ao professor Alternei (alternei@ufam.edu.br).

Rascunho do email:

>Olá, professor.
>
>Estamos muito contentes com a aceitação e entusiasmo do ICET em ajudar a Python Norte 2024 acontecer em Itacoatiara.
>A programação do evento se dará em 2 dias (27 e 28) em Setembro. Para realizar as atividades planejadas, solicitamos a reserva dos seguintes espaços:
>* (27/09) 3 laboratórios para a realização dos tutoriais, 1 auditório para Abertura e Keynote;
>* (28/09) 3 salas para a realização das palestras e do Job Fair, 1 auditório para Abertura, Keynotes e Palestras Relâmpago.
> Para os dois dias gostaríamos de solicitar a área externa (entrada) para o credenciamento.

>Atenciosamente,

**Comment by meu-bem** [comment]
Ele informou que vai solicitar.
Link dos emails: https://mail.google.com/mail/u/1/#sent/QgrcJHsThhfMjHwjjCZGBlJFdxFKcjHBdcL
