### ISSUE TITLE
Criar o documento para solicitar o auxilio da PSF (@julianyraiol)

### ISSUE THREAD

**Issue by julianyraiol** [PyNorte/pynorte2024-org#3]

**Comment by meu-bem** [comment]
Link do pré-documento: https://docs.google.com/document/d/19FMYUSB4GKA__Gzhd6yiXs5FmEvOY1n2pw9PnBFPc4k/edit
Items que faltam para enviar:
- Grant Amount Breakdown (divisão dos valores a serem solicitados)
- Budget and Revenues (Orçamentos e receitas até o momento)
- Conference Registration Page (página da compra de ingressos)
- Conference Prospectus (Documento de apresentação do evento em inglês)
- Link pro código de conduta no site
